on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: Run PHPCS inspection
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: Run PHPCS inspection
      uses: rtCamp/action-phpcs-code-review@v2.0.2
      env:
        GH_BOT_TOKEN: ${{ secrets.91c876d1975fa462fd57ce314d0cb35a011fe691 }}
        SKIP_FOLDERS: "tests,.github"
      with:
        args: "WordPress,WordPress-Core,WordPress-Docs"
